api_platform:
    title: Nettecamp 2019
    version: 1.0.0
    show_webby: false
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/config/api-platform/resources']
