doctrine:
    dbal:
        charset: utf8
        driver: pdo_pgsql
        host: '%env(DATABASE_HOST)%'
        dbname: postgres
        password: '%env(DATABASE_PASSWORD)%'
        user: postgres

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\'
                alias: App
