version: '3'

services:
  adminer:
    image: adminer
    ports:
      - 7999:8080
    volumes:
      - adminer:/tmp

  api:
    image: srigi/api
    build:
      context: .
      args:
        APP_DEBUG: $APP_DEBUG
        APP_ENV: $APP_ENV
        IS_PROD_BUILD: 0
        TIMEZONE: $TIMEZONE
    env_file:
      - .env
    volumes:
      - ./.docker/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./bin:/app/bin
      - ./config:/app/config
      - ./migrations:/app/migrations
      - ./public:/app/public
      - ./src:/app/src
      - ./var:/app/var

  migrations:
    image: srigi/api
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./.docker/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./config:/app/config
      - ./migrations:/app/migrations
      - ./src:/app/src
      - ./var:/app/var
    deploy:
      restart_policy:
        condition: on-failure
    command: 'wait-for-it -t 30 database:5432 -- bin/console doctrine:migrations:migrate --ansi --no-interaction'

  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - database:/var/lib/postgresql/data

  webserver:
    image: srigi/api/webserver
    build:
      context: .
      dockerfile: Dockerfile.webserver
      args:
        API_URL_PATH: $API_URL_PATH
        FCGI_READ_TIMEOUT: 3600s
        TIMEZONE: $TIMEZONE
        WEBSERVER_CONFIG: 'nginx.dev.conf'
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./public:/app/public

volumes:
  adminer:
  database:
